package eecs3311.group.p.Marketplace.model;

import java.time.LocalDateTime;

import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a user entity in the application.
 *
 * This class is mapped to the "users" table in the database.
 * It stores user credentials, profile information, and tokens for
 * email verification and password reset.
 *
 * Uses Lombok annotations {@link Data}, {@link NoArgsConstructor}, and {@link AllArgsConstructor}
 * to automatically generate getters, setters, constructors, equals, hashCode, and toString methods.
 */
@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * The unique identifier (primary key) for the user.
     * It is automatically generated by the database strategy (e.g., auto-increment).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user's unique and non-null username.
     * This is used for logging in.
     */
    @Column(unique = true, nullable = false)
    private String username;

    /**
     * The user's securely hashed password.
     * This field should never store a plain-text password.
     */
    @Column(nullable = false)
    private String passwordHash;

    /**
     * The user's email address.
     * Used for notifications, verification, and password resets.
     * Note: This field is also constrained to be unique in the database.
     */
    @Column(unique = true, nullable = false) // Added constraints from previous steps
    private String email;
    
    /**
     * A temporary code (e.g., 6-digits) sent to the user's email during signup
     * for account verification. It is expected to be nullified after use.
     */
    @Column(name = "verification_code")
    private String verificationCode;

    /**
     * A flag indicating whether the user has successfully verified their email address.
     * Defaults to false.
     */
    @Column(nullable = false)
    private boolean verified = false;

    /**
     * A unique token (e.g., UUID) generated when the user requests a password reset.
     * This token is sent to the user's email as part of a reset link.
     */
    @Column(name = "password_reset_token")
    private String passwordResetToken;

    /**
     * The timestamp indicating when the {@code passwordResetToken} will expire
     * and no longer be valid (e.g., 1 hour after creation).
     */
    @Column(name = "password_reset_token_expiry")
    private LocalDateTime passwordResetTokenExpiry;
}